name: Process libraries.json

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.EXCALIBOT_PAT_WORKFLOWS }}
      - name: regenrate-item-names
        run: node scripts/gen-item-names.mjs
      - name: Commit changes
        run: |
          FILE_CHANGED=$(git diff libraries.json)
          if [ ! -z "${FILE_CHANGED}" ]; then
            git config --global user.name 'Excalidraw Bot'
            git config --global user.email 'bot@excalidraw.com'
            git add .
            git commit -am "regenerate itemNames"
            git push
          fi
